INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ABACAVIR', 8.42, 'images\items\ABACAVIR.jpeg', 301);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ABACAVIR SOLUTION', 26.89, 'images\items\ABACAVIR SOLUTION.jpeg', 31);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ABIRATERONE', 32.45, 'images\items\ABIRATERONE.jpeg', 432);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ACETAZOLAMIDE', 35.26, 'images\items\ACETAZOLAMIDE.jpeg', 483);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ACYCLOVIR', 42.84, 'images\items\ACYCLOVIR.jpeg', 414);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ALFUZOSIN', 26.21, 'images\items\ALFUZOSIN.jpeg', 138);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('AMETHOCAINE', 16.01, 'images\items\AMETHOCAINE.jpeg', 36);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('AMLODIPINE', 8.37, 'images\items\AMLODIPINE.jpeg', 471);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ATORVASTATIN', 33.79, 'images\items\ATORVASTATIN.jpeg', 96);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('AZACITIDINE', 16.02, 'images\items\AZACITIDINE.jpeg', 396);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('BENZYDAMINE', 17.9, 'images\items\BENZYDAMINE.jpeg', 70);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('BENZYL BENZOATE', 30.98, 'images\items\BENZYL BENZOATE.jpeg', 167);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('BETAXOLOL', 25.88, 'images\items\BETAXOLOL.jpeg', 344);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('BUDESONIDE UDV', 31.1, 'images\items\BUDESONIDE UDV.jpeg', 157);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CANDESARTAN', 19.37, 'images\items\CANDESARTAN.jpeg', 51);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CARVEDILOL', 36.27, 'images\items\CARVEDILOL.jpeg', 278);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CEFPROZIL', 27.23, 'images\items\CEFPROZIL.jpeg', 430);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CETIRIZINE', 9.05, 'images\items\CETIRIZINE.jpeg', 371);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CIMETIDINE', 38.68, 'images\items\CIMETIDINE.jpeg', 52);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CITALOPRAM', 29.32, 'images\items\CITALOPRAM.jpeg', 13);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CLARITHROMYCIN', 45.55, 'images\items\CLARITHROMYCIN.jpeg', 329);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CLOMIFENE', 8.61, 'images\items\CLOMIFENE.jpeg', 334);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CLOZAPINE', 14.28, 'images\items\CLOZAPINE.jpeg', 344);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('DIAZEPAM', 42.43, 'images\items\DIAZEPAM.jpeg', 151);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('DICLOFENAC', 27.49, 'images\items\DICLOFENAC.jpeg', 380);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('DOXYCYCLINE', 36.08, 'images\items\DOXYCYCLINE.jpeg', 374);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('EFAVIRENZ', 37.57, 'images\items\EFAVIRENZ.jpeg', 413);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ERLOTINIB', 38.61, 'images\items\ERLOTINIB.jpeg', 57);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ETORICOXIB', 31.26, 'images\items\ETORICOXIB.jpeg', 268);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('FENTANYL', 37.05, 'images\items\FENTANYL.jpeg', 94);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('FLUOXETINE', 45.7, 'images\items\FLUOXETINE.jpeg', 45);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('GEMCITABINE', 20.98, 'images\items\GEMCITABINE.jpeg', 471);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('IBANDRONIC ACID', 43.13, 'images\items\IBANDRONIC ACID.jpeg', 301);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('GRANISETRON', 37.18, 'images\items\GRANISETRON.jpeg', 403);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('IBUPROFEN', 9.53, 'images\items\IBUPROFEN.jpeg', 435);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('IMATINIB', 31.34, 'images\items\IMATINIB.jpeg', 199);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('INSULIN  HUMALOG', 19.44, 'images\items\INSULIN  HUMALOG.jpeg', 347);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('INSULIN NOVOMIX', 6.86, 'images\items\INSULIN NOVOMIX.jpeg', 225);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ISOTRETINOIN', 41.39, 'images\items\ISOTRETINOIN.jpeg', 465);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('KETOCONAZOLE', 19.92, 'images\items\KETOCONAZOLE.jpeg', 453);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('LAMIVUDINE', 43.09, 'images\items\LAMIVUDINE.jpeg', 238);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('LANSOPRAZOLE', 11.73, 'images\items\LANSOPRAZOLE.jpeg', 41);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('LEVOFLOXACIN', 35.69, 'images\items\LEVOFLOXACIN.jpeg', 55);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('LOPERAMIDE', 13.27, 'images\items\LOPERAMIDE.jpeg', 301);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('MAGNESIUM CHLORIDE', 25.08, 'images\items\MAGNESIUM CHLORIDE.jpeg', 470);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('MELOXICAM', 18.85, 'images\items\MELOXICAM.jpeg', 431);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('METHYLPHENIDATE', 21.13, 'images\items\METHYLPHENIDATE.jpeg', 218);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('MIRTAZAPINE', 11.55, 'images\items\MIRTAZAPINE.jpeg', 95);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('MONTELUKAST', 23.78, 'images\items\MONTELUKAST.jpeg', 335);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('MOXIFLOXACIN', 30.82, 'images\items\MOXIFLOXACIN.jpeg', 352);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('NEVIRAPINE', 20.04, 'images\items\NEVIRAPINE.jpeg', 395);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('NYSTATIN', 23.44, 'images\items\NYSTATIN.jpeg', 191);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('OLANZAPINE', 19.95, 'images\items\OLANZAPINE.jpeg', 426);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('OLANZAPINE', 13.27, 'images\items\OLANZAPINE.jpeg', 128);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('OXYMETAZOLINE', 16.87, 'images\items\OXYMETAZOLINE.jpeg', 443);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PACLITAXEL', 22.14, 'images\items\PACLITAXEL.jpeg', 169);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PANTOPRAZOLE', 20.83, 'images\items\PANTOPRAZOLE.jpeg', 206);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PARACETAMOL', 12.55, 'images\items\PARACETAMOL.jpeg', 275);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PARACETAMOL CODEINE', 10.92, 'images\items\PARACETAMOL CODEINE.jpeg', 462);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PARACETAMOL IBUPROFEN', 38.89, 'images\items\PARACETAMOL IBUPROFEN.jpeg', 302);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PAROXETINE', 38.13, 'images\items\PAROXETINE.jpeg', 266);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PIOGLITAZONE', 40.97, 'images\items\PIOGLITAZONE.jpeg', 56);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('POTASSIUM CHLORIDE', 14.36, 'images\items\POTASSIUM CHLORIDE.jpeg', 257);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('PRAMIPEXOLE', 22.53, 'images\items\PRAMIPEXOLE.jpeg', 359);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('QUETIAPINE', 14.14, 'images\items\QUETIAPINE.jpeg', 401);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('QUINAPRIL', 33.73, 'images\items\QUINAPRIL.jpeg', 315);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('RISPERIDONE', 40.55, 'images\items\RISPERIDONE.jpeg', 94);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('RIVAROXABAN', 10.67, 'images\items\RIVAROXABAN.jpeg', 429);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('SENNA GLYCOSIDES', 27.68, 'images\items\SENNA GLYCOSIDES.jpeg', 330);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('SIMVASTATIN', 20.63, 'images\items\SIMVASTATIN.jpeg', 331);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('TAMOXIFEN', 18.04, 'images\items\TAMOXIFEN.jpeg', 31);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('TENOFOVIR', 21.24, 'images\items\TENOFOVIR.jpeg', 196);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('TIMOLOL DORZOLAMIDE', 22.03, 'images\items\TIMOLOL DORZOLAMIDE.jpeg', 418);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('TRAMADOL', 12.09, 'images\items\TRAMADOL.jpeg', 252);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('TRANEXAMIC', 14.81, 'images\items\TRANEXAMIC.jpeg', 199);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('VALACICLOVIR', 42.96, 'images\items\VALACICLOVIR.jpeg', 23);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('VALPROIC ACID', 39.11, 'images\items\VALPROIC ACID.jpeg', 464);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('VENLAFAXINE', 10.24, 'images\items\VENLAFAXINE.jpeg', 492);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ZIDOVUDINE', 7.33, 'images\items\ZIDOVUDINE.jpeg', 400);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('ZOLPIDEM', 25.39, 'images\items\ZOLPIDEM.jpeg', 366);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('BORTEZOMIB', 37.74, 'images\items\BORTEZOMIB.jpeg', 340);
INSERT INTO Items (itemName, itemPrice, itemImagePath, itemTotal) VALUES ('CABAZITAXEL', 10.16, 'images\items\CABAZITAXEL.jpeg', 389);
